#ifndef UIFONT_H
#define UIFONT_H

enum
{
    ////////////////Menu Structure/////////////////////
    UISTR_MENU_MAINMENU,
    UISTR_MENU_USERMANAGE,
    UISTR_MENU_SYSTEMSETTING,
    UISTR_MENU_USBMANAGE,
    UISTR_MENU_SYSINFOVIEW,
    UISTR_MENU_DATAVIEW,
    //UISTR_MENU_ALARMREMOVE,

    //>>UISTR_MENU_USERMANAGE-----------------------------------------------------<<		1
    UISTR_MENU_ENROLLNEW,
    //UISTR_MENU_ENROLLBACKUP,
    //UISTR_MENU_ENROLLDELETE,
    UISTR_MENU_ENROLLEDIT,
    UISTR_MENU_ENROLLDEL,
    //UISTR_MENU_MESSINFO,

    //>>UISTR_MENU_SYSINFOVIEW----------------------------------------------------<<		4
    UISTR_MENU_USERENROLLCOUNT,
    UISTR_MENU_FPENROLLCOUNT,
    //UISTR_MENU_PWDENROLLCOUNT,
    //UISTR_MENU_CARDENROLLCOUNT,
    //UISTR_MENU_GLOGCOUNT,
    //UISTR_MENU_MLOGCOUNT,
    //UISTR_MENU_USEDMEMORY,
    //UISTR_MENU_FREESPACES,
    UISTR_MENU_DEVICEINFO,
    //UISTR_MENU_USEDSPACES,

};

class QString;

void FONTDATABASE_INIT();
QString UISTR(int nIndex);


#endif // UIFONT_H
