#ifndef UIFONT_H
#define UIFONT_H

enum
{
    ////Menu Structure///////////////////////////////
    UISTR_MENU_MAINMENU,
    UISTR_MENU_ENROLLNEWFP,
    UISTR_MENU_ENROLLNEWPWD,
    UISTR_MENU_USERDATAVIEW,
    UISTR_MENU_SETTIME,
    UISTR_MENU_USBMANAGER,
    UISTR_MENU_OTHERINFO,

    ////UISTR_MENU_USBMANAGER///////////////////////////
    UISTR_MENU_ONEGLOGLOAD,
    UISTR_MENU_ALLGLOGLOAD,
    UISTR_MENU_ALLMANAGERGLOGLODA,
    UISTR_MENU_ONEUSERINFODOWN,
    UISTR_MENU_ALLUSERINFODOWN,
    UISTR_MENU_USERINFOUP,

    ////UISTR_MENU_OTHERINFO////////////////////////
    UISTR_MENU_USERGLOGINFO,
    UISTR_MENU_DEVICEINFO,


    ////UISTR_MENU_USERGLOGINFO////////////////////
    UISTR_MENU_USERENROLLCOUNT,
    UISTR_MENU_FPENROLLCOUNT,
    UISTR_MENU_PWDENROLLCOUNT,
    UISTR_MENU_GLOGCOUNT,
    UISTR_MENU_MLOGCOUNT,







    UISTR_MENU_USERMANAGE,
    UISTR_MENU_ENROLLBACKUP,
    UISTR_USER_NEW,
    UISTR_USER_NAME,
    UISTR_USER_ID,



};

class QString;

void FONTDATABASE_INIT();
QString UISTR(int nIndex);


#endif // UIFONT_H
